FROM gcr.io/distroless/static:nonroot AS final
LABEL io.buildpacks.stack.id="heroku-24"
LABEL io.buildpacks.base.homepage="https://github.com/devigned/wasm-packs"
LABEL io.buildpacks.base.maintainer="devigned"
