// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package types represents the imported interface "example:domain/types@0.3.0".
package types

import (
	"go.bytecodealliance.org/cm"
)

// Message represents the record "example:domain/types@0.3.0#message".
//
//	record message {
//		role: string,
//		content: string,
//	}
type Message struct {
	_       cm.HostLayout `json:"-"`
	Role    string        `json:"role"`
	Content string        `json:"content"`
}

// ChatRequest represents the record "example:domain/types@0.3.0#chat-request".
//
//	record chat-request {
//		model: string,
//		messages: list<message>,
//	}
type ChatRequest struct {
	_        cm.HostLayout    `json:"-"`
	Model    string           `json:"model"`
	Messages cm.List[Message] `json:"messages"`
}

// Annotation represents the record "example:domain/types@0.3.0#annotation".
//
//	record annotation {
//		annotation-type: string,
//		annotation-value: string,
//	}
type Annotation struct {
	_               cm.HostLayout `json:"-"`
	AnnotationType  string        `json:"annotation-type"`
	AnnotationValue string        `json:"annotation-value"`
}

// Choice represents the record "example:domain/types@0.3.0#choice".
//
//	record choice {
//		index: s32,
//		message: message,
//		finish-reason: string,
//	}
type Choice struct {
	_            cm.HostLayout `json:"-"`
	Index        int32         `json:"index"`
	Message      Message       `json:"message"`
	FinishReason string        `json:"finish-reason"`
}

// ChatResponse represents the record "example:domain/types@0.3.0#chat-response".
//
//	record chat-response {
//		id: string,
//		object: string,
//		created: s32,
//		choices: list<choice>,
//	}
type ChatResponse struct {
	_       cm.HostLayout   `json:"-"`
	ID      string          `json:"id"`
	Object  string          `json:"object"`
	Created int32           `json:"created"`
	Choices cm.List[Choice] `json:"choices"`
}

// Error represents the record "example:domain/types@0.3.0#error".
//
//	record error {
//		code: s32,
//		message: string,
//	}
type Error struct {
	_       cm.HostLayout `json:"-"`
	Code    int32         `json:"code"`
	Message string        `json:"message"`
}
