api = "0.10"

[buildpack]
id = "devigned/nodejs"
version = "0.0.1"
name = "Devigned Node.js"

[[buildpack.licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "3.4.11"

[[order.group]]
id = "heroku/nodejs-corepack"
version = "3.4.11"
optional = true

[[order.group]]
id = "heroku/nodejs-npm-engine"
version = "3.4.11"
optional = true

[[order.group]]
id = "heroku/nodejs-npm-install"
version = "3.4.11"

[[order.group]]
id = "wasm/nodejs"
version = "0.0.1"

[[metadata.targets]]
os = "linux"
arch = "amd64"

[[metadata.targets]]
os = "linux"
arch = "arm64"

[metadata.release]
image = { repository = "ghcr.io/devigned/buildpack-nodejs" }
