api = "0.10"

[buildpack]
id = "devigned/wasm"
version = "0.0.1"
name = "Wasm Buildpack"

[[buildpack.licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "wasm/wasm-tools"
version = "0.0.1"

[[order.group]]
id = "wasm/wasmtime-engine"
version = "0.0.1"

[[order.group]]
id = "heroku/nodejs-engine"
version = "3.4.11"

# [[order.group]]
# id = "heroku/nodejs-corepack"
# version = "3.4.11"
# optional = true

# [[order.group]]
# id = "heroku/nodejs-npm-engine"
# version = "3.4.11"
# optional = true

# [[order.group]]
# id = "heroku/nodejs-npm-install"
# version = "3.4.11"
# optional = true

# [[order.group]]
# id = "heroku/go"
# version = "0.5.6"

[[order.group]]
id = "wasm/wac-analyzer"
version = "0.0.1"
optional = true

[[order.group]]
id = "wasm/nodejs"
version = "0.0.1"
optional = true

[[order.group]]
id = "wasm/golang"
version = "0.0.1"
optional = true

[[order.group]]
id = "wasm/wac-composer"
version = "0.0.1"
optional = true

[[order.group]]
id = "wasm/wasm-finalizer"
version = "0.0.1"

[[metadata.targets]]
os = "linux"
arch = "amd64"

[[metadata.targets]]
os = "linux"
arch = "arm64"

[metadata.release]
image = { repository = "ghcr.io/devigned/buildpack-nodejs" }
