// Code generated by wit-bindgen-go. DO NOT EDIT.

package adder

// Exports represents the caller-defined exports from "example:domain/adder@0.3.0".
var Exports struct {
	// Add represents the caller-defined, exported function "add".
	//
	//	add: func(x: s32, y: s32) -> s32
	Add func(x int32, y int32) (result int32)
}
