// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package chat represents the exported interface "example:domain/chat@0.3.0".
package chat

import (
	"github.com/devigned/wasm-packs/compose/internal/example/domain/types"
)

// ChatRequest represents the type alias "example:domain/chat@0.3.0#chat-request".
//
// See [types.ChatRequest] for more information.
type ChatRequest = types.ChatRequest

// ChatResponse represents the type alias "example:domain/chat@0.3.0#chat-response".
//
// See [types.ChatResponse] for more information.
type ChatResponse = types.ChatResponse

// Error represents the type alias "example:domain/chat@0.3.0#error".
//
// See [types.Error] for more information.
type Error = types.Error
