// Code generated by wit-bindgen-go. DO NOT EDIT.

package chat

import (
	"github.com/devigned/wasm-packs/compose/internal/example/domain/types"
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "example:domain@0.3.0".

//go:wasmexport example:domain/chat@0.3.0#chat
//export example:domain/chat@0.3.0#chat
func wasmexport_Chat(request0 *uint8, request1 uint32, request2 *types.Message, request3 uint32) (result *cm.Result[ChatResponseShape, ChatResponse, Error]) {
	request := lift_ChatRequest((*uint8)(request0), (uint32)(request1), (*types.Message)(request2), (uint32)(request3))
	result_ := Exports.Chat(request)
	result = &result_
	return
}
