// Code generated by wit-bindgen-go. DO NOT EDIT.

package chat

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "example:domain/chat@0.3.0".
var Exports struct {
	// Chat represents the caller-defined, exported function "chat".
	//
	//	chat: func(request: chat-request) -> result<chat-response, error>
	Chat func(request ChatRequest) (result cm.Result[ChatResponseShape, ChatResponse, Error])
}
