name: build
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup-tools
        uses: buildpacks/github-actions/setup-tools@v5.8.9
      - name: setup-pack
        uses: buildpacks/github-actions/setup-pack@v5.8.9
      - name: Build and test
        run: |
          make build test
