name: build
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Pack CLI
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli
      - name: Build base images and create builder
        run: |
          ./base-images/build.sh wasm
          pack builder create wasm/demo-builder:wasm --config ../builders/wasm/builder.toml
      - name: Run compose buildpack
        run: |
          pack build test-wasm-compose --builder wasm/demo-builder:wasm --path apps/compose
      - name: Run individual buildpack
        run: |
          pack build test-wasm-individual --builder wasm/demo-builder:wasm --path apps/js
